# Generated by Django 4.0.3 on 2022-03-20 16:53

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GlucoseReading',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reading_uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('patient_uuid', models.UUIDField()),
                ('value', models.FloatField()),
                ('unit', models.CharField(choices=[('mmol/L', 'mmol/L'), ('mmol/L', 'mg/dL')], max_length=10)),
                ('recorded_at', models.DateTimeField()),
            ],
        ),
    ]
